aggregator: rnn
aggregator_path: ckpts/best_aggregator/checkpoints/best.ckpt
alpha: 0.5
batch_size: 256
ckpt_dir: adapt_step/recsys_model_gating/logs/fism/agg_freeze_False
data_dir: data
data_names:
- redditv1.5
decay: 0
dropout_prob: 0.1
embed_size: 4096
embed_update_batch_size: 2048
epochs: 1000
freeze_aggregator: false
freeze_llm_embed: true
ks:
- 1
- 5
- 10
- 50
label: labels_from_data_as_single_token
llm_embed_path: data/llm_embedding.pt
load_pretrained_weights: null
lr: 0.0001
max_len: 128
max_minutes: 180
negs: 1000
print_every: 2
recsys: fism
recsys_embed_size: 64
recsys_with_bias: true
test_only: false